Public Class ClsAvoidTriggerRecursion{
    Public Static Boolean Var_Static_PopulatingFinanceTeamMember = False;  
    Public Static Boolean Var_Static_tgr_Clause_Review = False; 
    Public Static Boolean Var_Static_tgr_Clause_ReviewEx1 = False; 
    Public Static Boolean Var_Static_PopulatePllAndEngrTLApprover = False;
    
    Public Static Boolean Var_Static_ManageFinanceDetailTrgr = true;  
    
    
}