/*
Description     :This test class covers the GEESRiskPrescreeningExtension Controller class
                 which include covering of various action function and business logic function. 
Functional Area : Risk Management
Created By      : Susmita Prabhu
Release         : Re-org 
                  This class has been created to cover prescreening functionality upon trigger/wf deactivation
*/


@isTest
private with sharing class GEESRiskPrescreeningExtensionTest_deact { 

    static testMethod void runPrescreeningTest() {
    }
}