/*
Type Name [Class/Trigger/Page Name] : Test Class - Test_BMGlobal
Used Where ?                        : Test class
Purpose/Overview                    : Test class written for the apex class BMGlobal
Functional Area                     : Big Machines
Author                              : Sanjay Kumar Patidar
Created Date                        : 18th May 2012
Test Class Name                     : 

Change History -
Date Modified   : Developer Name        : Method/Section Modified/Added     : Purpose/Overview of Change
*/

@isTest
private class Test_BMGlobal 
	{
	static testMethod void Test1() 
		{
     	BMGlobal cons = new BMGlobal();
     	}
	}